class Item:
    def __init__(
        self,
        entry=None,
        class_=None,
        subclass=None,
        sound_override_subclass=None,
        name=None,
        display_id=None,
        quality=None,
        flags=None,
        flags_extra=None,
        buy_count=None,
        buy_price=None,
        sell_price=None,
        inventory_type=None,
        allowable_class=None,
        allowable_race=None,
        item_level=None,
        required_level=None,
        required_skill=None,
        required_skill_rank=None,
        required_spell=None,
        required_honor_rank=None,
        required_city_rank=None,
        required_reputation_faction=None,
        required_reputation_rank=None,
        max_count=None,
        stackable=None,
        container_slots=None,
        stats_count=None,
        stat_type1=None,
        stat_value1=None,
        stat_type2=None,
        stat_value2=None,
        stat_type3=None,
        stat_value3=None,
        stat_type4=None,
        stat_value4=None,
        stat_type5=None,
        stat_value5=None,
        stat_type6=None,
        stat_value6=None,
        stat_type7=None,
        stat_value7=None,
        stat_type8=None,
        stat_value8=None,
        stat_type9=None,
        stat_value9=None,
        stat_type10=None,
        stat_value10=None,
        scaling_stat_distribution=None,
        scaling_stat_value=None,
        dmg_min1=None,
        dmg_max1=None,
        dmg_type1=None,
        dmg_min2=None,
        dmg_max2=None,
        dmg_type2=None,
        armor=None,
        holy_res=None,
        fire_res=None,
        nature_res=None,
        frost_res=None,
        shadow_res=None,
        arcane_res=None,
        delay=None,
        ammo_type=None,
        ranged_mod_range=None,
        spell_id1=None,
        spell_trigger1=None,
        spell_charges1=None,
        spell_ppm_rate1=None,
        spell_cooldown1=None,
        spell_category1=None,
        spell_category_cooldown1=None,
        spell_id2=None,
        spell_trigger2=None,
        spell_charges2=None,
        spell_ppm_rate2=None,
        spell_cooldown2=None,
        spell_category2=None,
        spell_category_cooldown2=None,
        spell_id3=None,
        spell_trigger3=None,
        spell_charges3=None,
        spell_ppm_rate3=None,
        spell_cooldown3=None,
        spell_category3=None,
        spell_category_cooldown3=None,
        spell_id4=None,
        spell_trigger4=None,
        spell_charges4=None,
        spell_ppm_rate4=None,
        spell_cooldown4=None,
        spell_category4=None,
        spell_category_cooldown4=None,
        spell_id5=None,
        spell_trigger5=None,
        spell_charges5=None,
        spell_ppm_rate5=None,
        spell_cooldown5=None,
        spell_category5=None,
        spell_category_cooldown5=None,
        bonding=None,
        description=None,
        page_text=None,
        language_id=None,
        page_material=None,
        start_quest=None,
        lock_id=None,
        material=None,
        sheath=None,
        random_property=None,
        random_suffix=None,
        block=None,
        item_set=None,
        max_durability=None,
        area=None,
        map_=None,
        bag_family=None,
        totem_category=None,
        socket_color1=None,
        socket_content1=None,
        socket_color2=None,
        socket_content2=None,
        socket_color3=None,
        socket_content3=None,
        socket_bonus=None,
        gem_properties=None,
        required_disenchant_skill=None,
        armor_damage_modifier=None,
        duration=None,
        item_limit_category=None,
        holiday_id=None,
        script_name=None,
        disenchant_id=None,
        food_type=None,
        min_money_loot=None,
        max_money_loot=None,
        flags_custom=None,
        verified_build=None,
    ):
        self.entry = entry
        self.class_ = class_
        self.subclass = subclass
        self.sound_override_subclass = sound_override_subclass
        self.name = name
        self.display_id = display_id
        self.quality = quality
        self.flags = flags
        self.flags_extra = flags_extra
        self.buy_count = buy_count
        self.buy_price = buy_price
        self.sell_price = sell_price
        self.inventory_type = inventory_type
        self.allowable_class = allowable_class
        self.allowable_race = allowable_race
        self.item_level = item_level
        self.required_level = required_level
        self.required_skill = required_skill
        self.required_skill_rank = required_skill_rank
        self.required_spell = required_spell
        self.required_honor_rank = required_honor_rank
        self.required_city_rank = required_city_rank
        self.required_reputation_faction = required_reputation_faction
        self.required_reputation_rank = required_reputation_rank
        self.max_count = max_count
        self.stackable = stackable
        self.container_slots = container_slots
        self.stats_count = stats_count
        self.stat_type1 = stat_type1
        self.stat_value1 = stat_value1
        self.stat_type2 = stat_type2
        self.stat_value2 = stat_value2
        self.stat_type3 = stat_type3
        self.stat_value3 = stat_value3
        self.stat_type4 = stat_type4
        self.stat_value4 = stat_value4
        self.stat_type5 = stat_type5
        self.stat_value5 = stat_value5
        self.stat_type6 = stat_type6
        self.stat_value6 = stat_value6
        self.stat_type7 = stat_type7
        self.stat_value7 = stat_value7
        self.stat_type8 = stat_type8
        self.stat_value8 = stat_value8
        self.stat_type9 = stat_type9
        self.stat_value9 = stat_value9
        self.stat_type10 = stat_type10
        self.stat_value10 = stat_value10
        self.scaling_stat_distribution = scaling_stat_distribution
        self.scaling_stat_value = scaling_stat_value
        self.dmg_min1 = dmg_min1
        self.dmg_max1 = dmg_max1
        self.dmg_type1 = dmg_type1
        self.dmg_min2 = dmg_min2
        self.dmg_max2 = dmg_max2
        self.dmg_type2 = dmg_type2
        self.armor = armor
        self.holy_res = holy_res
        self.fire_res = fire_res
        self.nature_res = nature_res
        self.frost_res = frost_res
        self.shadow_res = shadow_res
        self.arcane_res = arcane_res
        self.delay = delay
        self.ammo_type = ammo_type
        self.ranged_mod_range = ranged_mod_range
        self.spell_id1 = spell_id1
        self.spell_trigger1 = spell_trigger1
        self.spell_charges1 = spell_charges1
        self.spell_ppm_rate1 = spell_ppm_rate1
        self.spell_cooldown1 = spell_cooldown1
        self.spell_category1 = spell_category1
        self.spell_category_cooldown1 = spell_category_cooldown1
        self.spell_id2 = spell_id2
        self.spell_trigger2 = spell_trigger2
        self.spell_charges2 = spell_charges2
        self.spell_ppm_rate2 = spell_ppm_rate2
        self.spell_cooldown2 = spell_cooldown2
        self.spell_category2 = spell_category2
        self.spell_category_cooldown2 = spell_category_cooldown2
        self.spell_id3 = spell_id3
        self.spell_trigger3 = spell_trigger3
        self.spell_charges3 = spell_charges3
        self.spell_ppm_rate3 = spell_ppm_rate3
        self.spell_cooldown3 = spell_cooldown3
        self.spell_category3 = spell_category3
        self.spell_category_cooldown3 = spell_category_cooldown3
        self.spell_id4 = spell_id4
        self.spell_trigger4 = spell_trigger4
        self.spell_charges4 = spell_charges4
        self.spell_ppm_rate4 = spell_ppm_rate4
        self.spell_cooldown4 = spell_cooldown4
        self.spell_category4 = spell_category4
        self.spell_category_cooldown4 = spell_category_cooldown4
        self.spell_id5 = spell_id5
        self.spell_trigger5 = spell_trigger5
        self.spell_charges5 = spell_charges5
        self.spell_ppm_rate5 = spell_ppm_rate5
        self.spell_cooldown5 = spell_cooldown5
        self.spell_category5 = spell_category5
        self.spell_category_cooldown5 = spell_category_cooldown5
        self.bonding = bonding
        self.description = description
        self.page_text = page_text
        self.language_id = language_id
        self.page_material = page_material
        self.start_quest = start_quest
        self.lock_id = lock_id
        self.material = material
        self.sheath = sheath
        self.random_property = random_property
        self.random_suffix = random_suffix
        self.block = block
        self.item_set = item_set
        self.max_durability = max_durability
        self.area = area
        self.map_ = map_
        self.bag_family = bag_family
        self.totem_category = totem_category
        self.socket_color1 = socket_color1
        self.socket_content1 = socket_content1
        self.socket_color2 = socket_color2
        self.socket_content2 = socket_content2
        self.socket_color3 = socket_color3
        self.socket_content3 = socket_content3
        self.socket_bonus = socket_bonus
        self.gem_properties = gem_properties
        self.required_disenchant_skill = required_disenchant_skill
        self.armor_damage_modifier = armor_damage_modifier
        self.duration = duration
        self.item_limit_category = item_limit_category
        self.holiday_id = holiday_id
        self.script_name = script_name
        self.disenchant_id = disenchant_id
        self.food_type = food_type
        self.min_money_loot = min_money_loot
        self.max_money_loot = max_money_loot
        self.flags_custom = flags_custom
        self.verified_build = verified_build

    def __str__(self):
        return str(self.__dict__)
